name: blog

dependencies:
  - python
  - blinker
  - docutils
  - feedgenerator
  - ghp-import
  - Jinja2
  - Markdown
  - MarkupSafe
  - pelican==4.8.0
  - Pygments
  - python-dateutil
  - pytz
  - six
  - Unidecode
