name: blog

dependencies:
  - python=3.9
  - blinker==1.4
  - docutils==0.16
  - feedgenerator==1.9.1
  - ghp-import==1.0.0
  - Jinja2==2.11.2
  - Markdown==3.3.3
  - MarkupSafe==1.1.1
  - pelican==4.2.0
  - Pygments==2.7.2
  - python-dateutil==2.8.1
  - pytz==2020.1
  - six==1.15.0
  - Unidecode==1.1.1
