baseURL = 'https://aniruddhadeb.com'
languageCode = 'en-us'
title = 'Aniruddha Deb'
theme = 'paper'

disqusShortname = 'aniruddha-deb'   # use disqus comments

[taxonomies]
  category = 'categories'
  tag = 'tags'

[[menu.main]]
  name = "Blog"
  url = "/articles/"
  weight = 1
[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light
  paginate = 100

  dateFormat = '2006-01-02 15:04'
  publishDateFormat = '2006-01-02 15:04'

  # header social icons
  twitter = 'hairband_dude'               # twitter.com/YOUR_TWITTER_ID
  github = 'Aniruddha-Deb'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = '/pic_anime.png'                 # gravatar email or image url
  name = 'Aniruddha Deb'
  bio = "Free Your Mind"

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
# gravatarCdn = 'GRAVATAR_CDN_LINK'                      # e.g. 'https://cdn.v2ex.com/gravatar/'
# graphCommentId = "GRAPH_COMMENT_ID" # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally

[permalinks]
  posts = '/:year/:slug'

